### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by sbonaime** [andreiulinici/fleet-management#9]
Hi,

I try to start fleet-management on a Debian server and also on my mac. I had exactly the same error 
```
npm install
audited 290 packages in 1.769s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜  fleet-management git:(development) ✗ node start
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/home/resadocker/fleet-management/start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

What can I do ? 

Thank you

**Comment by sbonaime** [comment]
If I use
>npm start

I have the following error
````
> fleet-management@1.0.6 start /Users/bonaime/git/fleet-management
> node server.js

/Users/bonaime/git/fleet-management/server.js:161
app.use(expressValidator());
        ^

TypeError: expressValidator is not a function
    at Object.<anonymous> (/Users/bonaime/git/fleet-management/server.js:161:9)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fleet-management@1.0.6 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fleet-management@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
